spring:
    datasource:
        driver-class-name: org.h2.Driver
        hikari:
            jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
            username: sa
            password: sa
            connection-timeout: 30000
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 600000
            max-lifetime: 1800000
            pool-name: HikariPool-1
            initialization-fail-timeout: 0