spring:
  application:
    name: eureka-server

server:
  port: 8761
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: 132435!
    key-store-type: JKS
    key-password: 132435!
    client-auth: need

eureka:
  server:
    enable-self-preservation: true
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

