spring:
  threads:
    virtual:
      enabled: true
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;DATABASE_TO_UPPER=true;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:
logging.level:
  org.hibernate.SQL: debug
  org.springframework.jdbc: debug