POST http://146.56.115.136:8083/connectors
Content-Type: application/json

{
  "name" : "insertOnly-connect3",
  "config" :{
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "transforms.unwrap.delete.handling.mode": "drop",
    "database.history.kafka.topic": "schema-changes.employees3",
    "transforms": "unwrap",
    "bootstrap.servers": "kafka00:9092,kafka01:9092,kafka02:9092",
    "include.schema.changes": "false",
    "topic.prefix": "insert-only3",
    "schema.history.internal.kafka.topic": "history-never3",
    "transforms.unwrap.drop.tombstones": "false",
    "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
    "database.allowPublicKeyRetrieval": "true",
    "database.user": "root",
    "database.server.id": "184054",
    "database.name": "employees",
    "database.history.kafka.bootstrap.servers": "kafka00:9092",
    "schema.history.internal.kafka.bootstrap.servers": "kafka00:9092,kafka01:9092,kafka02:9092",
    "transforms.unwrap.add.headers": "operation,source.ts_ms",
    "database.port": "3308",
    "database.useSSL": "false",
    "database.hostname": "146.56.115.136",
    "database.connectionTimeZone": "UTC",
    "database.password": 1234,
    "table.include.list": ".*",
    "snapshot.mode": "schema_only",
    "lock.mode": "none"
  }
}

###
POST http://146.56.115.136:8083/connectors
Content-Type: application/json

{
"name" : "insertOnly-connect",
"config" :{
"connector.class": "io.debezium.connector.mysql.MySqlConnector",
"transforms.unwrap.delete.handling.mode": "drop",
"database.history.kafka.topic": "schema-changes.employees",
"transforms": "unwrap",
"bootstrap.servers": "kafka00:9092,kafka01:9092,kafka02:9092",
"include.schema.changes": "false",
"topic.prefix": "all-copy",
"schema.history.internal.kafka.topic": "history-never",
"transforms.unwrap.drop.tombstones": "false",
"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
"database.allowPublicKeyRetrieval": "true",
"database.user": "root",
"database.server.id": "184054",
"database.name": "employees",
"database.history.kafka.bootstrap.servers": "kafka00:9092",
"schema.history.internal.kafka.bootstrap.servers": "kafka00:9092,kafka01:9092,kafka02:9092",
"transforms.unwrap.add.headers": "operation,source.ts_ms",
"database.port": "3308",
"database.useSSL": "false",
"database.hostname": "146.56.115.136",
"database.connectionTimeZone": "UTC",
"database.password": 1234,
"table.include.list": ".*",
"snapshot.mode": "initial",
"lock.mode": "none"
}
}